### ISSUE TITLE
Logging in with TLS is broken

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#1]
Whenever I attempt to login with TLS enabled, Visual Studio throws up an AggregateException Error, of "Unable to login" Stepping through the code, it seems to fail with the initial response.

**Comment by Nikey646** [comment]
Woops, i'll look through that, what is the exact Inner Exception object of AggregateException, and a StackTrace if you have one?

**Comment by Nikey646** [comment]
Nevermind about my previous questions, forgot that was an exception i threw when the response from the login method wasn't "ok". The issue was that i was using the `TcpClient`s stream to send and receive data, despite wrapping the `NetworkStream` from the `TcpClient` in a `SslStream`. Not entirely sure why this didn't just perform insecure operations with the `NetworkStream` from the `TcpClient`, but i was able to connect and receive data using the above commit.
