### ISSUE TITLE
[Question] Helper Vndb Flags

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#11]
What do you mean by helper vndb flags? Do you mean to have a few sets of pre-configured flags the user might need, such as the "basic" and "details" flags, or am I misunderstanding what you meant? I want to figure this out, so I can work on implementing this.

**Comment by Nikey646** [comment]
They are already implemented in the .Net Core version, but since it would be more then a simple change (Like what the `IEnumerable` interface for `RoobObject<T>` was) i won't be back porting it to code that will soon be obsolete, since .Net Core libraries can be used from .Net 4.x.

Pretty much everything listed in the [Readme.md](https://github.com/Nikey646/VndbSharp/blob/ReadMeFun/README.md) has been completed or is in progress in the .Net Core version.

I haven't been committing the changes because more often then not I've gone back and made a breaking change and I'm also still deciding on how some features will work. Once I finish the .Net Core version and done some basic testing to ensure everything works I'll commit it.

**Comment by Nikey646** [comment]
This is now implemented in the master branch as of https://github.com/Nikey646/VndbSharp/commit/6f2677084b05dfbf86a14385ccae297eb47df124
