### ISSUE TITLE
[Feature Request] Add support for Staff

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#16]
The Staff array of objects was recently implemented into the API under the "get vn" command. I would appreciate it if you could add support for it in the near future.

[https://vndb.org/d11#5.1](https://vndb.org/d11#5.1)

**Comment by Nikey646** [comment]
[Features/GetStaff](https://github.com/Nikey646/VndbSharp/tree/Features/GetStaff) branch has the start of the Staff implementation, it's missing the Staff API Endpoint (get staff) at this point in time because i got distracted when implementing it, and haven't gone back to it yet.

The Staff metadata on the VN object is there conceptually, but i haven't tested it yet.

**Comment by micah686** [comment]
when you merge the Features/GetStaff branch into master, I'll close this pull request, since Features/GetStaff should have most if not all implementations of the "get staff" command.

**Comment by micah686** [comment]
Is there anything that needs to be added to the GetStaff branch before you want to merge it? I've tested the staff, and I haven't noticed any problems.

(I would like GetStaff merged into master, because master has the most current fixes, but I can't use the GetStaff commands on the master branch)

**Comment by Nikey646** [comment]
I'll look into it in a bit (I should have some free time to do so today)
