### ISSUE TITLE
Add a tag/trait converter

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#27]
I'm not sure if this is quite in the scope of this project, but it would be nice to have a converter for tags and traits where you could give it a tag or trait ID, and it would return with the members of the tag or trait.

**Comment by Nikey646** [comment]
What do you mean by members? The parent / child relationship of the tags/traits :?

**Comment by micah686** [comment]
The ones outlined in [vndb.org/d14](vndb.org/d14), basically {name, description, meta, vns, cat,aliases, parents, chars}.
So if you have a tag id related to a specific vn, you can get the name and description and such from the tag id.

**Comment by Nikey646** [comment]
So you want a helper method to automatically download and find a tag/trait from an Id?

I would prefer not to add that, because it would require that the tag/trait dumps be stored somewhere, and i would rather not have the library be doing I/O stuff, which would leave in-memory as the only real choice, and that is a bad choice because it means re-downloading the dump every time the application is restarted.

I wouldn't mind adding support to get them from a collection, but at that point you would need all of them to be loaded into memory, when using a database and just selecting the ones you need from it would be more efficient.

**Comment by micah686** [comment]
Ok. I wasn't sure if it would work or not. I guess I'll make my own converter to get the names and descriptions. I had a feeling it might not be feasible, since you don't want to save anything on the local filesystem without the user's permission, and obviously loading the whole dump into memory is a bad idea.
