### ISSUE TITLE
[Feature Suggestion] Allow downloading the Tag/Trait dumps' .json

### ISSUE THREAD

**Issue by micah686** [Nikey646/VndbSharp#7]
What would you think about adding an option to download the .json from the tag or trait dumps to a specified folder that the user selects? Just an option I'd like you to consider

**Comment by Nikey646** [comment]
Sorry, but i don't see the value in providing that option.

As it stands, the implementation gives you an almost raw representation of the Tag / Json dumps that allow you to do anything with it. You could store them in a database using your favorite ORM, a document store like MongoDb, or even manually via SQLite / similar. You could write them to .json, using the already referenced Newtonsoft.Json library, or one of the various built in Json parsers. Hell, store them in .xml for all i care!

What i'm getting at, is there is more then one way to store the data provided, and i don't think the library should give the impression "this is the recommended way" by providing a way to download the data as json to disk.

This could also become more problematic when i get around to switching it to a .Net Core class library and set the targeting to a .Net Standard version, since the library will inherently work on any version of .Net that meets the minimum .Net Standard i use (Which will be the lowest possible without compromising features) and different platforms offer different File APIs, which could become problematic. There might be a wrapper that overlays all the various file systems for me, but i haven't explored that aspect yet :P

If you think there is still value in providing built in way to save the file to disc, despite what I've mentioned, i will gladly consider it again.

**Comment by micah686** [comment]
Ok, fair enough. Another programmer could always export the results into a usable format for them.
